### PR TITLE
Add passive voice (rebase)

### PR DESCRIPTION
**Pull request by nerixim**
Addressed comment at https://github.com/rossmeissl/verbs/pull/27#issuecomment-633622572

### CODE REVIEW

**Comment by nerixim** [comment]
@rossmeissl
I've rebased and changed the wording.
Github Action failed to install Ruby https://github.com/rossmeissl/verbs/pull/35/checks?sha=261ea39ca3434b863aa25a2cda9b59d820649b9d so I tried upgrading actions/setup Ruby but it stopped working altogether.
Maybe try switching to https://github.com/ruby/setup-ruby as proposed at https://github.com/actions/setup-ruby/issues/80?

**Comment by rossmeissl** [comment]
Hi @nerixim I just added you as a collaborator on this repo — does that allow you to make the fix yourself? If not I can try to do it myself just might take a bit longer. Thanks!

**Comment by nerixim** [comment]
@rossmeissl Thanks! Turned out it was an indent problem 🤦

**Review by rossmeissl — APPROVED** [review]
Hi @nerixim thank you!
Please add yourself to the Acknowledgements section of the Readme (unless you'd rather not be there) and then go ahead and merge!

I really appreciate your help!

**Comment by rossmeissl** [comment]
This closes #27 — thank you @jeidsath for your early work on this.

I've released the new passive voice feature in 2.3.0.

Thanks again @nerixim !

**Pull request merged**
