### PR TITLE
Add passive voice

### PR DESCRIPTION
**Pull request by jeidsath**
Adds the passive voice and some tests.

I used ":voice" instead of ":diathesis" as the much more common term.

### CODE REVIEW

**Comment by rossmeissl** [comment]
@jeidsath would you mind rebasing this against master and changing back to `diathesis` to reduce ambiguity?

**Comment by nerixim** [comment]
@jeidsath @rossmeissl 
Hi 👋 If both of your are can I address your comment to merge this PR?
> @jeidsath would you mind rebasing this against master and changing back to diathesis to reduce ambiguity?

**Comment by rossmeissl** [comment]
@nerixim please do!

**Comment by rossmeissl** [comment]
Closed in https://github.com/rossmeissl/verbs/pull/35

**Pull request closed without merging**
